service: online-exam-serverless

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  environment:
    EXAMS_TABLE: ${self:service}-exams-${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource:
        - "arn:aws:dynamodb:${opt:region, 'us-east-1'}:*:table/${self:service}-exams-${opt:stage, 'dev'}"

functions:
  createExam:
    handler: backend/create_exam.lambda_handler
    events:
      - http:
          path: exams/create
          method: post
          cors: true

  submitAnswers:
    handler: backend/submit_answers.lambda_handler
    events:
      - http:
          path: exams/submit
          method: post
          cors: true

  getResults:
    handler: backend/get_results.lambda_handler
    events:
      - http:
          path: exams/results
          method: get
          cors: true

resources:
  Resources:
    ExamsDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-exams-${opt:stage, 'dev'}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
